### ISSUE TITLE
Individual links cannot be clicked

### ISSUE THREAD

**Issue by zxhycxq** [xyflow/web#264] opened 2023-11-20 03:47 UTC
### Code of Conduct

- [X] I have read and agree to the xyflow contributor [Code of Conduct](https://github.com/xyflow/web/blob/main/CODE_OF_CONDUCT.md)

### Which site are you suggesting a change for?

reactflow.dev

### What content is affected by this change?

![image](https://github.com/xyflow/web/assets/11674203/ae987c0a-d4a6-4a09-b5a0-0f54e0d34384)

### What part(s) of the article would you like to see updated?

All links clicked normally

### Additional information

To avoid being influenced by other factors, I am using a browser's modeless approach。
Edge、Chrome

**Comment by zxhycxq** [comment] 2023-11-20 04:01
may be this link is "https://reactflow.dev/api-reference/types/node-props",and others is "/learn/"?

**Comment by hayleigh-dot-dev** [comment] 2024-01-02 15:02
Closing this issue as a duplicate of [this](https://github.com/xyflow/web/issues/227). This seems to be an unfortunate limitation of nextra.

**Closed by hayleigh-dot-dev** 2024-01-02 15:02 UTC
